In [1]:
import tensorflow as tf

In [6]:
#tf.maths.abs - used to get the absolute value in tensor
tensor=tf.constant([1,2,-4,-6,10])
print(tf.math.abs(tensor))
#if we have conplex number then the absolute value becomes the root over a square + b square
complex_tensor=tf.constant([12+5j,3+4j])
print((tf.math.abs(complex_tensor)))

tf.Tensor([ 1  2  4  6 10], shape=(5,), dtype=int32)
tf.Tensor([13.  5.], shape=(2,), dtype=float64)


In [10]:
#tf.add is  used to add two tensor, if they are having dimensionality compablity
tensor1=tf.constant([1,2,3,4,5,6])
tensor2=tf.constant([6,5,4,3,2,1])
print(tf.add(tensor1,tensor2))

#tf.subtract is used to subtract two tensors
print(tf.subtract(tensor1,tensor2))

#tf.divide is used to divide two tensor
print(tf.divide(tensor1,tensor2))

#tf

tf.Tensor([7 7 7 7 7 7], shape=(6,), dtype=int32)
tf.Tensor([-5 -3 -1  1  3  5], shape=(6,), dtype=int32)
tf.Tensor([0.16666667 0.4        0.75       1.33333333 2.5        6.        ], shape=(6,), dtype=float64)
