In [1]:
import tensorflow as tf

In [2]:
#to add extra axis to your tensor that will have the length of one
tensor_3d=tf.constant([
    [
        [1,2,0],
        [3,5,-1]
    ],
    [
        [10,2,0],
        [1,0,2]
    ],
    [
        [2,1,9],
        [4,3,32]
    ]
])

print(f"the shape before expanding : {tensor_3d.shape}")
#adding extra axis to the tensor
print(f" the shape after extending the dimensions : {tf.expand_dims(tensor_3d,axis=0).shape}")


the shape before expanding : (3, 2, 3)
 the shape after extending the dimensions : (1, 3, 2, 3)


In [3]:
#to compress the dimension of the tensor i.e opposite to the tf.expand_dims
tensor_3d=tf.constant([
    [
        [1,2,0],
        [3,5,-1]
    ],
    [
        [10,2,0],
        [1,0,2]
    ],
    [
        [2,1,9],
        [4,3,32]
    ]
])

print(f"the shape after shriking the tensor is : \n ")
tf.squeeze(tensor_3d)

#3:00:30 

the shape after shriking the tensor is : 
 


<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  0],
        [ 3,  5, -1]],

       [[10,  2,  0],
        [ 1,  0,  2]],

       [[ 2,  1,  9],
        [ 4,  3, 32]]])>

In [7]:
#reshaping the tensor

tensor_3d=tf.constant([
    [
        [1,2,0],
        [3,5,-1]
    ],
    [
        [10,2,0],
        [1,0,2]
    ],
    [
        [2,1,9],
        [4,3,32]
    ],
        [
        [2,1,9],
        [4,3,32]
    ]
])
print(f"the shape of the tensor before reshaping is {tensor_3d.shape}")

print(f"the shape of the tensor after reshaping is {tf.reshape(tensor_3d,[6,4])}")

the shape of the tensor before reshaping is (4, 2, 3)
the shape of the tensor after reshaping is [[ 1  2  0  3]
 [ 5 -1 10  2]
 [ 0  1  0  2]
 [ 2  1  9  4]
 [ 3 32  2  1]
 [ 9  4  3 32]]


In [11]:
#tf.concat is use to concat tensor in 1d 
t1=tf.constant([[1,2,3],[4,5,6]])
t2=tf.constant([[7,8,9],[10,11,12]])
tf.concat([t1,t2],0)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])>

In [ ]:
#3:12:29