In [2]:
import tensorflow as tf

In [4]:
#tf.linalg.matmul - it is used to calculate the matrix wise multiplication
x1=tf.constant([
    [1,2,3],
    [4,5,6]
])
x2=tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

tf.linalg.matmul(
    x1,x2
)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[30, 36, 42],
       [66, 81, 96]])>

In [6]:
print("the transpose of the matrix x1 is : ")
tf.transpose(x1)

the transpose of the matrix x1 is : 


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]])>

In [7]:
#sparse matrix- matrix build of mostly zeroes, benifit of this is that now while performing computation tensorflow knows that it is mostly made of zeroes and so 
# this knowlege will make the computation more optimized


In [9]:
#inband method
tensor_2d=tf.constant(
    [
        [1,-2,0],
        [3,5,100],
        [1,5,6],
        [2,3,8]
    ],
    dtype=tf.float64
)

tf.linalg.band_part(tensor_2d,0,0)

<tf.Tensor: shape=(4, 3), dtype=float64, numpy=
array([[1., 0., 0.],
       [0., 5., 0.],
       [0., 0., 6.],
       [0., 0., 0.]])>

In [14]:
#tf.linalg.inv - used to compute the inverse of the matrix
tensor=tf.constant([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]],dtype=tf.float32)

# tf.linalg.inv(tensor)