#we will learn some basics of tensor

source- https://www.youtube.com/watch?v=IA3WxTTPXqQ


In [1]:
import tensorflow as tf


In [2]:
tensor1=tf.constant(4)
print(tensor1)

tf.Tensor(4, shape=(), dtype=int32)


In [3]:
tensor2=tf.constant([1,2,3])
print(tensor2)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [6]:
tensor3=tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
)
print(tensor3)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [9]:
print(f"the shape of zero d tensor is {tensor1.shape}")
print(f"the shape of 1 d tensor is {tensor2.shape}")
print(f"the shape of 2 d tensor is {tensor3.shape}")

the shape of zero d tensor is ()
the shape of 1 d tensor is (3,)
the shape of 2 d tensor is (3, 3)


#converting numpy array to tensor

In [13]:
import numpy as np 


In [11]:
npArray=np.array([1,2,3])
print(npArray)

[1 2 3]


In [12]:
newTensor=tf.convert_to_tensor(npArray)
newTensor

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

#method to create identity matrix tensor


In [16]:
eye_tensor=tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.float32,
    name=None
)
eye_tensor

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [17]:
eye_tensor=tf.eye(
    num_rows=3,
    num_columns=None,
    batch_shape=None,
    dtype=tf.dtypes.bool,
    name=None
)
eye_tensor

<tf.Tensor: shape=(3, 3), dtype=bool, numpy=
array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])>

#method to create a tensor of a paticular type

In [19]:
tensor_fill=tf.fill(
    [3,3],2,name=None
)
tensor_fill

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])>

#method to create tensor matrix with all ones

In [21]:
tensor_ones=tf.ones(
    [3,3],
    dtype=tf.dtypes.float32,
    name=None
)
tensor_ones

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

#crearing a one matrix from a pre available matrix, but all the values will be one

In [23]:
tensor_one_like=tf.ones_like(
    tensor3
)
tensor_one_like

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])>

#creating a tensor with all zeroes

In [25]:
tensor_zeroes=tf.zeros_like(
    [4,4],
    dtype=tf.dtypes.float32,
    name=None
)
tensor_zeroes

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0., 0.], dtype=float32)>

#rank method to find the rank of the tensor

In [26]:
tf.rank(tensor3)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

#size method- it is used to calcualte the number of elenment in the tensor/ size of the tensor

In [27]:
tf.size(tensor3)

<tf.Tensor: shape=(), dtype=int32, numpy=9>

#tf.tandom.normal -  it is used to generate a random tensor matrix with given shape, the values are filled using the data from a normal distribution

In [30]:
random_tensor=tf.random.normal(
    [3,4],
    mean=100,
    stddev=1,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[100.44578   99.07645   98.75683   99.138596]
 [100.53236  100.82927  101.15516   98.90594 ]
 [ 98.60504   99.112175  99.617226 101.357635]], shape=(3, 4), dtype=float32)


#tf.random.uniform - used to generate random tensor matrix with a given  min and max range

In [35]:
random_tensor_uniform=tf.random.uniform(
    [5,],
    minval=0,
    maxval=100,
    dtype=tf.dtypes.int32
)
print(random_tensor_uniform)

tf.Tensor([48 13 61 27 93], shape=(5,), dtype=int32)


In [ ]:
#stop at - 1:07:22