In [1]:
import tensorflow as tf

In [2]:
tensor_2d=tf.constant([
        [1,2,3],
        [3,7,4],
        [1,5,6],
        [2,8,4]
])

print(f"the shape of the tensor is {tensor_2d.shape}")



the shape of the tensor is (4, 3)


In [6]:
# tensor_2d=tf.constant([
#         [1,2,],
#         [3,7,4],
#         [1,],
#         [2,8,4]
# ])

#for above tensor, the tensor is not rectangular, this is a non acceptable condition when dealing with tensor
#when we have non reactangular data set , we use ragged tensor
tensor_2d_ragged=tf.ragged.constant([
        [1,2,],
        [3,7,4],
        [1,],
        [2,8,4]
])
print(f"the shape of tagged tensor is {tensor_2d_ragged.shape}")

the shape of tagged tensor is (4, None)


In [16]:
#tf.ragged.boolean_mask -  used to drop the values as specified in the mask vector

tensor=tf.ragged.boolean_mask([
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
,mask=[
    [True,False,True],
    [False,False,False],
    [True,False,False]
]).to_list()

tensor



[[1, 3], [], [7]]

In [21]:
#tf.RaggedTensor- it is used to generate tensor by using a predefined tensor and a lenght tensor to define what lenght of data we will probe
print(tf.RaggedTensor.from_row_lengths(
    values=[3, 1, 4, 1, 5, 9, 2],
    row_lengths=[4, 0, 2, 1]))

<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9], [2]]>


In [22]:
#tf.RaggedTensor.from_row_limits - used to geenrate tensor by using a row limit
#it uses some sort of two pointer limit to build the tensor
print(tf.RaggedTensor.from_row_splits(
    values=[3, 1, 4, 1, 5, 9, 2],
    row_splits=[0, 4, 4, 6, 7]))

<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9], [2]]>


In [26]:
#to create a sparse tensor 
tensor_sparse=tf.sparse.SparseTensor(
    indices=[[1,1],[3,4]], values=[25,53],dense_shape=[5,6]
)

print(tensor_sparse)

SparseTensor(indices=tf.Tensor(
[[1 1]
 [3 4]], shape=(2, 2), dtype=int64), values=tf.Tensor([25 53], shape=(2,), dtype=int32), dense_shape=tf.Tensor([5 6], shape=(2,), dtype=int64))


In [28]:
#below code gives a tensor  with fiiting the values 25 and 53 at specified location
tf.sparse.to_dense(tensor_sparse)

<tf.Tensor: shape=(5, 6), dtype=int32, numpy=
array([[ 0,  0,  0,  0,  0,  0],
       [ 0, 25,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 53,  0],
       [ 0,  0,  0,  0,  0,  0]])>