In [1]:
#importing the libraries
import tensorflow as tf

In [2]:
index_tensor=tf.constant([1,4,2,7,8,19])
print(index_tensor)

tf.Tensor([ 1  4  2  7  8 19], shape=(6,), dtype=int32)


In [9]:
#to get the first four elenment of above tensor
print(index_tensor[0:4])
print(index_tensor[1:4])
print(index_tensor[2:4])
#to get the alternate elenemnt from the tensor
print(index_tensor[0:6:2])


tf.Tensor([1 4 2 7], shape=(4,), dtype=int32)
tf.Tensor([4 2 7], shape=(3,), dtype=int32)
tf.Tensor([2 7], shape=(2,), dtype=int32)
tf.Tensor([1 2 8], shape=(3,), dtype=int32)


In [10]:
tensor_2d=tf.constant(
    [
        [1,2,3],
        [4,5,6],
        [7,8,9]
    ]
)

In [14]:
#picking a paticular row in 2d tensor
print(f"to get the first 3 row and first 2 columns {tensor_2d[ 0:3,0:2 ]}")
print(f"to get the first 2 rows and all the elenments {tensor_2d[ 0:3,: ]}")


to get the first 3 row and first 2 columns [[1 2]
 [4 5]
 [7 8]]
to get the first 2 rows and all the elenments [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
tensor_3d=tf.constant(
    [
        [
            [1,2,0],
            [3,5,-1]
        ],
        [
            [10,2,0],
            [1,0,2]
        ],
        [
            [2,1,9],
            [4,-3,32]
        ]
    ]
)



In [16]:
#to get the first 2 rows of 2*3 tensor
print(tensor_3d[ 0,: ,: ])

tf.Tensor(
[[ 1  2  0]
 [ 3  5 -1]], shape=(2, 3), dtype=int32)
