In [2]:
import tensorflow as tf

In [3]:
#tf.maths.abs - used to get the absolute value in tensor
tensor=tf.constant([1,2,-4,-6,10])
print(tf.math.abs(tensor))
#if we have conplex number then the absolute value becomes the root over a square + b square
complex_tensor=tf.constant([12+5j,3+4j])
print((tf.math.abs(complex_tensor)))

tf.Tensor([ 1  2  4  6 10], shape=(5,), dtype=int32)
tf.Tensor([13.  5.], shape=(2,), dtype=float64)


In [6]:
#tf.add is  used to add two tensor, if they are having dimensionality compablity
tensor1=tf.constant([1,2,3,4,5,6])
tensor2=tf.constant([6,5,4,3,2,1])
print(tf.add(tensor1,tensor2))

#tf.subtract is used to subtract two tensors
print(tf.subtract(tensor1,tensor2))

#tf.divide is used to divide two tensor
print(tf.divide(tensor1,tensor2))

#tensor multiplication
tf1=tf.constant([1,2,3,4])
tf2=tf.constant([4,3,2,1])
print(f"the multiplied output of the tensor is {tf.multiply(tf1,tf2)}")

tf.Tensor([7 7 7 7 7 7], shape=(6,), dtype=int32)
tf.Tensor([-5 -3 -1  1  3  5], shape=(6,), dtype=int32)
tf.Tensor([0.16666667 0.4        0.75       1.33333333 2.5        6.        ], shape=(6,), dtype=float64)
the multiplied output of the tensor is [4 6 6 4]


In [13]:
# tf.math.argmax - returns the index of the elenment witht the highest values
tensor=tf.constant([
    [2,20,30,3,6],
    [3,11,16,1,8],
    [14,45,23,5,27]
]
)
print(f"the shape of the tensor is {tensor.shape}")
print(f"the index of max value is {tf.math.argmax(tensor),0}")
#by passing 0 above we are finxing the axis here, row in this case, and then we compare each elenment in a paticular column
# as an output we get a tensor which has the index of each index corrsoponding to the highest value in the column


the shape of the tensor is (3, 5)
the index of max value is (<tf.Tensor: shape=(5,), dtype=int64, numpy=array([2, 2, 0, 2, 2], dtype=int64)>, 0)


In [14]:
#tf.math.equal is used to compare two tensor and give another tensor as output based on comparision
tensor1=tf.constant([1,2,3,4,5,6])
tensor2=tf.constant([6,5,4,3,2,1])
print(f"the output of tf.math.equal is as follow {tf.math.equal(tensor1,tensor2)}")

the output of tf.math.equal is as follow [False False False False False False]


In [17]:
#tf.math.pow is used to raise the values of one tensor with respect to the values provided in the another tensor
ten1=tf.constant([
    [1,2,3],
    [4,5,6]
])
ten2=tf.constant([
    [3,2,1],
    [6,5,4]
])
print(f"the output of the pow function is \n {tf.math.pow(ten1,ten2)}")

the output of the pow function is 
 [[   1    4    3]
 [4096 3125 1296]]


In [26]:
#tf.maht.reduce_sum - it is used to compute the sum of elenment along a paticular axis
tensor=tf.constant([
    [2,20,30,3,6],
    [3,11,16,1,8],
    [14,45,23,5,27]
])
print(f'the shape of aboev tensor is {tensor.shape}')
print(f"the output of tf.math.reduce_sum is as follow \n {tf.math.reduce_sum(tensor,axis=0, keepdims=False, name=None)}")

the shape of aboev tensor is (3, 5)
the output of tf.math.reduce_sum is as follow 
 [19 76 69  9 41]


In [27]:
#tf.math.top_k - it is used get top k elenments for a input tensor
print(tf.math.top_k(tensor))

TopKV2(values=<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[30],
       [16],
       [45]])>, indices=<tf.Tensor: shape=(3, 1), dtype=int32, numpy=
array([[2],
       [2],
       [1]])>)
