In [1]:
import tensorflow as tf

In [2]:
#to add extra axis to your tensor that will have the length of one
tensor_3d=tf.constant([
    [
        [1,2,0],
        [3,5,-1]
    ],
    [
        [10,2,0],
        [1,0,2]
    ],
    [
        [2,1,9],
        [4,3,32]
    ]
])

print(f"the shape before expanding : {tensor_3d.shape}")
#adding extra axis to the tensor
print(f" the shape after extending the dimensions : {tf.expand_dims(tensor_3d,axis=0).shape}")


the shape before expanding : (3, 2, 3)
 the shape after extending the dimensions : (1, 3, 2, 3)


In [3]:
#to compress the dimension of the tensor i.e opposite to the tf.expand_dims
tensor_3d=tf.constant([
    [
        [1,2,0],
        [3,5,-1]
    ],
    [
        [10,2,0],
        [1,0,2]
    ],
    [
        [2,1,9],
        [4,3,32]
    ]
])

print(f"the shape after shriking the tensor is : \n ")
tf.squeeze(tensor_3d)

#3:00:30 

the shape after shriking the tensor is : 
 


<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  0],
        [ 3,  5, -1]],

       [[10,  2,  0],
        [ 1,  0,  2]],

       [[ 2,  1,  9],
        [ 4,  3, 32]]])>

In [4]:
#reshaping the tensor

tensor_3d=tf.constant([
    [
        [1,2,0],
        [3,5,-1]
    ],
    [
        [10,2,0],
        [1,0,2]
    ],
    [
        [2,1,9],
        [4,3,32]
    ],
        [
        [2,1,9],
        [4,3,32]
    ]
])
print(f"the shape of the tensor before reshaping is {tensor_3d.shape}")

print(f"the shape of the tensor after reshaping is {tf.reshape(tensor_3d,[6,4])}")

the shape of the tensor before reshaping is (4, 2, 3)
the shape of the tensor after reshaping is [[ 1  2  0  3]
 [ 5 -1 10  2]
 [ 0  1  0  2]
 [ 2  1  9  4]
 [ 3 32  2  1]
 [ 9  4  3 32]]


In [5]:
#tf.concat is use to concat tensor in 1d 
t1=tf.constant([[1,2,3],[4,5,6]])
t2=tf.constant([[7,8,9],[10,11,12]])
tf.concat([t1,t2],0)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])>

In [17]:
#3:12:29

#inverse of a square tensor 
tensor3=tf.constant([
    [1,-2,0],
    [3,5,100],
    [1,5,6]
],dtype=tf.float32
)

print(f"the shape of above tensor is {tensor3.shape}")

inverse_tensor3=tf.linalg.inv(tensor3)

print(f"the invese tensor for above is {inverse_tensor3}")

inverse_tensor3@tensor3

the shape of above tensor is (3, 3)
the invese tensor for above is [[ 0.7413249  -0.01892742  0.3154574 ]
 [-0.12933755 -0.00946371  0.1577287 ]
 [-0.01577287  0.01104101 -0.01735016]]


<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 1.0000000e+00,  1.7881393e-07,  2.8610229e-06],
       [ 1.4901161e-08,  1.0000000e+00,  1.0728836e-06],
       [ 0.0000000e+00, -3.7252903e-09,  9.9999988e-01]], dtype=float32)>

In [21]:
#tf.svd function is used to get singular, left singular and right singular vector
tensor_2d=tf.constant([
        [2,1,9],
        [4,3,32]
    ], dtype=tf.float32)

print("the output for svd of above tensor is : \n")

s,u,v=tf.linalg.svd(tensor_2d)
print(f"the value of s is \n : {s}")
print(f"the value of u i s\n : {u}")
print(f"the value of v is \n : {v}")

the output for svd of above tensor is : 

the value of s is 
 : [33.67913    0.8466116]
the value of u i s
 : [[-0.27428895 -0.96164733]
 [-0.96164733  0.27428895]]
the value of v is 
 : [[-0.13050126 -0.97581714]
 [-0.09380384 -0.16392463]
 [-0.9870007   0.14460188]]


In [24]:
#3:12

#tf.stack method
t1=tf.constant([
    [1,2,3],
    [4,5,6]
    ])
t2=tf.constant([
    [7,8,9],
    [10,11,12]
    ])

#when we specify axis=0, we are stacking the tensor row wise i.e we will stack one tensor above other in row's direction
print("the output of tf.stack([t1,t2] , axis=0) , \n")
tf.stack([t1,t2],axis=0)

#when we have more tensor, it will get stakced in the same way
print("the output of tf.stack([t1,t2,t1] , axis=0) is: \n ")
tf.stack([t1,t2,t1] , axis=0)

the output of tf.stack([t1,t2] , axis=0) , 

the output of tf.stack([t1,t2,t1] , axis=0) is: 
 


<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[ 1,  2,  3],
        [ 4,  5,  6]]])>

In [31]:
#tf.pad- it is used to provide pading as a tensor for another tensor
t=tf.constant([
    [1,2,3],
    [4,5,6]
])

padding=tf.constant([
    [1,1],
    [2,2]
])

padding2=tf.constant([
    [1,1],
    [2,3]
])

#by using below function we are able to pad the t tensor with a constant value of 3 around it
print("the output for the padding fuction is : \n") 
print(tf.pad(t,padding,"CONSTANT",constant_values=3))

#the interpretation for the number of padding on each side is defined using the padding tensor
#in padding tensor it says 1,1 which means one row above and one row below tensor t, the second line says that 
#2,2 whcih signifies 2 collumns on left and two on right 

print("the output for the padding fuction is : \n") 
tf.pad(t,padding2,"CONSTANT",constant_values=3)




the output for the padding fuction is : 

tf.Tensor(
[[3 3 3 3 3 3 3]
 [3 3 1 2 3 3 3]
 [3 3 4 5 6 3 3]
 [3 3 3 3 3 3 3]], shape=(4, 7), dtype=int32)
the output for the padding fuction is : 



<tf.Tensor: shape=(4, 8), dtype=int32, numpy=
array([[3, 3, 3, 3, 3, 3, 3, 3],
       [3, 3, 1, 2, 3, 3, 3, 3],
       [3, 3, 4, 5, 6, 3, 3, 3],
       [3, 3, 3, 3, 3, 3, 3, 3]])>

In [35]:
#to perform complex slicing we can use tf.geather function 
tensor1=tf.constant(['a0',"a1","a2","a3","a4","a5"])

#to get the elenments from a1 to a4
print(tf.gather(tensor1, [1,2,3,4]))

#to get the elenmets a1 a3 and a5
print(tf.gather(tensor1,[1,3,5]))

tf.Tensor([b'a1' b'a2' b'a3' b'a4'], shape=(4,), dtype=string)
tf.Tensor([b'a1' b'a3' b'a5'], shape=(3,), dtype=string)
